# -*- coding: utf-8 -*-
"""Copy of week_03_workshop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IBi2G-YG0TjZDAmBmrDSgT4mKggVMk8_

---
title: "Workshop: Data Visualizations with the Ames Housing Dataset"
---

## Introduction

In this workshop, you'll apply your knowledge of data visualization using the Ames housing dataset.

In the first section, you'll create simple plots to explore various aspects of the dataset.

In the second section, you'll practice fixing code errors and improving code readability.

In the third section, you'll create plots using a for loop.

In the fourth section, you'll create a multivariate plot and interpret your findings.

The first two sections should be completed together in your group. The last two sections should be completed individually.

## Part 1: Exploratory Data Visualization

Consider the following questions about the Ames housing dataset. For each question, create a simple plot that addresses the question. Then make a comment on interpreting the plot. Your plots do not have to be elegant; focus on selecting the appropriate type of visualization for each question. (No need to customize axes, labels, etc.)

Variable Documentation:
1. https://vincentarelbundock.github.io/Rdatasets/doc/openintro/ames.html
2. https://jse.amstat.org/v19n3/decock/DataDocumentation.txt

First, import the necessary libraries and read in the dataset:
"""

import pandas as pd
import plotly.express as px
pd.set_option('display.max_columns', None)
ames = pd.read_csv("https://raw.githubusercontent.com/the-graph-courses/pbb_q4_2024_materials/refs/heads/main/week_03_workshop/data/ames.csv")
ames.columns = ames.columns.str.replace(".", "_")

ames.columns

"""1. **What is the relationship between the size of the house and the price?** (This will be done for you in class.)
   - Variables: `Lot_Area`, `price`
"""

# Create a scatter plot of Lot_Area vs. price
px.scatter(ames, x='Lot_Area', y='price')

"""There's little or no relationship between the lot area and price. Relatively small lot areas can vary greatly in price.

2. **Are houses originally built earlier in the 1900s more expensive than those built later in the century?**
   - Variables: `Year_Built`, `price`
"""

# Create a plot to explore the relationship between Year_Built and price
px.scatter(ames, x='Year_Built', y='price')

"""Houses originally built earlier in the 1900s have similar price with those built later in the century until 1980s when the prices started to rise.

3. **What is the most common type of primary exterior material?**
   - Variable: `Exterior_1st`
"""

# Create a plot to show the distribution of Exterior_1st
px.histogram(ames, x='Exterior_1st')

"""Vinyl Siding

4. **How does the price vary across different exterior types?**
   - Variables: `Exterior_1st`, `price`
"""

# Create a plot to show how price varies across Exterior_1st
px.box(ames, y="price", x="Exterior_1st", color="Exterior_1st")

"""VinylSd, BrkFace and metalSd have higher variability, with more outliers in the higher price ranges.
CemntBd has the highest median price.
Wd Sdng, MetalSd, and AsbShng tend to have lower median prices.

5. **Which neighborhoods have the highest proportions of Single-family Detached homes?**
   - Variables: `Neighborhood`, `Bldg_Type`
"""

# Create a plot to show the proportions of Single-family Detached homes across neighborhoods
px.histogram(
    ames,
    x='Neighborhood',
    color='Bldg_Type'
)

"""North Ames

## Part 2: Visualization with a For Loop

The plot below shows the distribution of the Roof style (`Roof_Style`) variable faceted by the slope of the property (`Land_Slope`).
"""

px.histogram(ames, x="Roof_Style", color="Land_Slope", facet_col="Land_Slope")

"""Recreate the same set of plots but using a for loop to iterate over the `Land_Slope` variable. The values for land slope are:

- **Gtl**: Gentle slope

- **Mod**: Moderate slope

- **Sev**: Severe slope

For each land slope category, create a plot showing the distribution of `Roof_Style`.
"""

# Use a for loop to create the plots
land_slope = ["Gtl", "Mod", "Sev"]

for slope in land_slope:
    ames_slope = ames.query("Land_Slope == @slope")
    fig = px.histogram(
        ames_slope,
        x="Roof_Style",
        color="Land_Slope",
        facet_col="Land_Slope",

    )
    fig.show()

"""## Part 3: Multivariate Plot Individual Assignment

For this section, you will work individually. Your chosen plot should not be the same as those of your group members.

- Look through the dataset and decide on three or four variables that could be visualized on a single plot (or on a faceted plot).

- Create a multivariate plot that visualizes these variables.

- Write a brief interpretation of any findings you can deduce from the plot.
"""

# Create your multivariate plot
px.scatter(ames, x="area", y='price', color="Lot_Shape", facet_col="Lot_Shape")

"""There is similar tendency regardless of the lot shape, i.e. price increases with increasing the area.

## Part 4: Optional Challenge

### Part 4a: Fixing Errors

The following code chunk attempts to create a stacked bar chart of central air conditioning by heating quality, but it contains several syntax errors.

### Instructions:

a. Identify and correct the syntax errors in the script so that it runs correctly.

b. Run the corrected code and observe the output.

c. Interpret the resulting plot.
"""

# First we use the replace method to change values according to the mapping
# We have not taught this yet, but you should be able to read and understand the gist of it

# Define a dictionary to map the values (replace with their full names)
heating_qc_labels = {
    "Ex": ["Excellent"],
    "Gd": ["Good"],
    "TA": ["Average/Typical"],
    "Fa": ["Fair"],
    "Po": ["Poor"]
}
central_air_LABEL = {'N':['No'], 'Y':['Yes']}
# Apply the mapping to the DataFrame
ames = ames.assign(
    Heating_QC_full=lambda df: df.Heating_QC.replace(heating_qc_labels),
    Central_Air_full=lambda df: df.Central_Air.replace(central_air_LABEL),
)

# Create the plot with the updated DataFrame
fig = px.histogram(
    ames,
    y="Central_Air_full",
    color="Heating_QC_full",
    barnorm="percent",
    color_discrete_sequence=["#d9534f", "#e39283", "#e8c590", "#a3c9a8", "#5cb85c"],
    category_orders={
        "Heating_QC_full": ["Poor", "Fair", "Average/Typical", "Good", "Excellent"],
    },
    labels={
        "Central_Air_full": "",
        "Heating_QC_full": "Heating Quality",
    },
    title="Central Air Conditioning by Heating Quality in Ames Housing",
)
fig

"""
### Part 4b: Exterior Condition by Exterior Type

Following the example above, create a horizontal percent-stacked bar chart showing the relationship between the type of exterior wall material (`Exterior_1st`) and the condition of the exterior wall (`Exter_Cond`).

- Your **y-axis** should be the `Exterior_1st` variable.

- The **color-axis** should be the `Exter_Cond` variable, and the legend should show these values in the following order: ["Poor", "Fair", "Average/Typical", "Good", "Excellent"]

- Use the same color scheme as in the example above.

- Your plot should have an appropriate title."""

fig = px.histogram(
    ames,
    y="Exterior_1st",
    color="Exter_Cond",
    barnorm="percent",
    color_discrete_sequence=["#d9534f", "#e39283", "#e8c590", "#a3c9a8", "#5cb85c"],
    category_orders={
        "Exter_Cond": ["Poor", "Fair", "Average/Typical", "Good", "Excellent"],
    },
    labels={
        "Exterior_1st": "exterior wall material",

    },
    title="Relationship between the type of exterior wall material and the condition of the exterior wall",
)
fig